# Generated by Django 2.0.6 on 2018-06-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.District')),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governance_level', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAffl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.District')),
            ],
        ),
        migrations.CreateModel(
            name='LocalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No Description')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.Local')),
                ('localType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.LocalType')),
            ],
        ),
        migrations.CreateModel(
            name='MinisterialOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolitcalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('description', models.CharField(default='No Description', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.Occupation'),
        ),
        migrations.AddField(
            model_name='individual',
            name='political_affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.GroupAffl'),
        ),
        migrations.AddField(
            model_name='individual',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.Rank'),
        ),
        migrations.AddField(
            model_name='groupaffl',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='political_registry.GroupType'),
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='political_registry.Publication'),
        ),
    ]
